# bazel/BUILD
package(default_visibility = ["//visibility:public"])

exports_files([
    "toolchain.bzl",
    "toolchain_config.bzl",
    "transitions.bzl",
    "wasm_toolchain.bzl",
    "extensions.bzl",
    "embed_data.bzl",
])
